apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  labels:
    app: nginx-pod
spec:
  replicas: 3
  selector:
    matchLabels:
      env: demo
  template:
    metadata:
      name: nginx-pod
      labels:
        env: demo
        type: front-end
    spec:
      containers:
        - name: nginx-container
          image: nginx
          ports:
            - containerPort: 80
