apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp-pod
spec:
  containers:
    - name: myapp-container
      image: busybox
      command: ["sh", "-c", "echo the app is running && sleep 2"]
      env:
        - name: FIRSTNAME
          value: "palani"
  initContainers:
    - name: init-myservice
      image: busybox
      command: ["sh", "-c"]
      args:
        [
          "until nslookup myservice.default.svc.cluster.local;do echo waitng for service;sleep 2; done",
        ]
    - name: init-mydb
      image: busybox
      command: ["sh", "-c"]
      args:
        [
          "until nslookup myservice.default.svc.cluster.local;do echo waitng for service;sleep 2; done",
        ]
