apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity-required
  labels:
    name: nginx-affinity-required
spec:
  containers:
  - name: nginx-affinity-required
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        preferrance:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - ssd
