apiVersion: v1
kind: Pod
metadata:
  name: nginx-toleration
  labels:
    name: nginx-toleration
spec:
  containers:
  - name: nginx-toleration
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
