apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-new
  name: nginx-new
spec:
  containers:
  - image: nginx
    name: nginx-new
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  nodeSelector:
    gpu: "false"

