apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity-preferred
  labels:
    name: nginx-affinity-preferred
spec:
  containers:
  - name: nginx-affinity-preferred
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - hdd
