apiVersion: v1
kind: Pod
metadata:
  name: nginx-affinity-req-pre-exists
  labels:
    name: nginx-affinity-req-pre-exists
spec:
  containers:
  - name: nginx-affinity-req-pre-exists
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 8080
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: Exists
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: disktype
            operator: Exists