apiVersion: v1
kind: Pod
metadata:
  name: nginx-manual-schedule
  labels:
    name: nginx
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
  nodeName: cka-cluster3-worker2