apiVersion: v1
kind: Pod
metadata:
  name: health-probe-demo
spec:
  containers:
  - name: myapp
    image: my-app-image
    livenessProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    readinessProbe:
      httpGet:
        path: /ready
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 10
    startupProbe:
      httpGet:
        path: /startup
        port: 8080
      failureThreshold: 30
      periodSeconds: 10
    resources:
        limits:
          memory: "128Mi"
          cpu: "500m"