apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
  labels:
    env: demo
spec:
  type: LoadBalancer
  selector:
    env: demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
