apiVersion: certificates.k8s.io/v1
kind: CertificateSigningRequest
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"certificates.k8s.io/v1","kind":"CertificateSigningRequest","metadata":{"annotations":{},"name":"newadmin"},"spec":{"expirationSeconds":86400,"request":"<key>","signerName":"kubernetes.io/kube-apiserver-client","usages":["client auth"]}}
  creationTimestamp: "2025-03-06T19:52:49Z"
  name: newadmin
  resourceVersion: "347090"
  uid: b1f7f54a-6bab-4e34-9c0f-7a3a121fb0eb
spec:
  expirationSeconds: 86400
  extra:
    authentication.kubernetes.io/credential-id:
    - X509SHA256=4c4f5f5a8d2444f9888e66d766d4bcc4b2c478724dad2fd5973b4267d84d771a
  groups:
  - kubeadm:cluster-admins
  - system:authenticated
  request: <key>
  signerName: kubernetes.io/kube-apiserver-client
  usages:
  - client auth
  username: kubernetes-admin
status:
  certificate: <cert>
  conditions:
  - lastTransitionTime: "2025-03-06T19:57:55Z"
    lastUpdateTime: "2025-03-06T19:57:55Z"
    message: This CSR was approved by kubectl certificate approve.
    reason: KubectlApprove
    status: "True"
    type: Approved
