apiVersion: v1
kind: Pod
metadata:
  name: memory-stress-pod
  namespace: mem-example
spec:
  containers:
  - name: stress-container
    image: polinux/stress
    command: ["stress", "--vm", "1", "--vm-bytes", "150M"]
    resources:
      limits:
        memory: 100Mi
        cpu: "500Mi"